INSERT INTO questions (text, quiz_id) VALUES ('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla felis dui, sodales et pulvinar ac, tincidunt nec dolor. Aenean imperdiet orci pretium lectus scelerisque ultricies.', 1);
INSERT INTO questions (text, quiz_id) VALUES ('Fusce vestibulum feugiat molestie. Aenean vulputate arcu ex, sed semper ante pharetra non. Ut cursus urna non pharetra mollis. Aliquam vel facilisis ipsum, quis pharetra eros.', 1);
INSERT INTO questions (text, quiz_id) VALUES ('Maecenas convallis mollis risus in dapibus.', 1);
INSERT INTO questions (text, quiz_id) VALUES ('Aliquam viverra tempor orci a convallis.', 2);
INSERT INTO questions (text, quiz_id) VALUES ('Donec scelerisque, ipsum ut consequat elementum, libero purus scelerisque tortor, placerat consectetur sapien tellus quis elit.', 2);
INSERT INTO questions (text, quiz_id) VALUES ('Sed pellentesque quam auctor, tempus orci at, elementum diam.', 2);
INSERT INTO questions (text, quiz_id) VALUES ('Suspendisse et metus in ex suscipit consequat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 3);
INSERT INTO questions (text, quiz_id) VALUES ('Cras blandit ipsum sit amet diam hendrerit aliquet.', 3);
INSERT INTO questions (text, quiz_id) VALUES ('Ut sed tortor risus. Donec aliquam mollis porttitor. Cras quis metus at augue condimentum tincidunt tempor sit amet arcu.', 3);
INSERT INTO questions (text, quiz_id) VALUES ('Suspendisse volutpat urna eu orci facilisis faucibus. Sed faucibus tellus in quam scelerisque porttitor.', 4);
INSERT INTO questions (text, quiz_id) VALUES ('Maecenas ac dui id tellus elementum maximus id dictum lacus. Nunc dapibus iaculis ullamcorper.', 4);
INSERT INTO questions (text, quiz_id) VALUES ('Nunc arcu nisl, tempus vitae mauris porttitor, faucibus varius mi.', 4);
INSERT INTO questions (text, quiz_id) VALUES ('Morbi ultricies at dui a sollicitudin.', 4);
INSERT INTO questions (text, quiz_id) VALUES ('Maecenas ornare eros et convallis vestibulum.', 4);
INSERT INTO questions (text, quiz_id) VALUES ('Sed eget neque a justo mattis eleifend.', 8);
INSERT INTO questions (text, quiz_id) VALUES ('Donec nisl turpis, ultricies at velit id, ultricies porta lorem. Nullam non fermentum turpis. Aliquam viverra tempor orci a convallis.', 8);
INSERT INTO questions (text, quiz_id) VALUES ('Aenean imperdiet orci pretium lectus scelerisque ultricies. Mauris efficitur ut tortor eget rhoncus.', 9);
INSERT INTO questions (text, quiz_id) VALUES ('Nulla felis dui, sodales et pulvinar ac, tincidunt nec dolor.', 9);
INSERT INTO questions (text, quiz_id) VALUES ('Fusce justo est, blandit non tortor et, maximus tincidunt urna.', 9);
INSERT INTO questions (text, quiz_id) VALUES ('Aenean vulputate arcu ex, sed semper ante pharetra non. Ut cursus urna non pharetra mollis.', 9);
