INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla felis dui, sodales et pulvinar ac, tincidunt nec dolor. Aenean imperdiet orci pretium lectus scelerisque ultricies.', 1);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Fusce vestibulum feugiat molestie. Aenean vulputate arcu ex, sed semper ante pharetra non. Ut cursus urna non pharetra mollis. Aliquam vel facilisis ipsum, quis pharetra eros.', 1);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Maecenas convallis mollis risus in dapibus.', 1);
INSERT INTO answers (is_answer, text, question_id) VALUES (true, 'Aliquam viverra tempor orci a convallis.', 1);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Donec scelerisque, ipsum ut consequat elementum, libero purus scelerisque tortor, placerat consectetur sapien tellus quis elit.', 2);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Sed pellentesque quam auctor, tempus orci at, elementum diam.', 2);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Suspendisse et metus in ex suscipit consequat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 2);
INSERT INTO answers (is_answer, text, question_id) VALUES (true, 'Cras blandit ipsum sit amet diam hendrerit aliquet.', 2);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Ut sed tortor risus. Donec aliquam mollis porttitor. Cras quis metus at augue condimentum tincidunt tempor sit amet arcu.', 3);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Suspendisse volutpat urna eu orci facilisis faucibus. Sed faucibus tellus in quam scelerisque porttitor.', 3);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Maecenas ac dui id tellus elementum maximus id dictum lacus. Nunc dapibus iaculis ullamcorper.', 3);
INSERT INTO answers (is_answer, text, question_id) VALUES (true, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla felis dui, sodales et pulvinar ac, tincidunt nec dolor. Aenean imperdiet orci pretium lectus scelerisque ultricies.', 3);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Fusce vestibulum feugiat molestie. Aenean vulputate arcu ex, sed semper ante pharetra non. Ut cursus urna non pharetra mollis. Aliquam vel facilisis ipsum, quis pharetra eros.', 4);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Maecenas convallis mollis risus in dapibus.', 4);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Aliquam viverra tempor orci a convallis.', 4);
INSERT INTO answers (is_answer, text, question_id) VALUES (true, 'Donec scelerisque, ipsum ut consequat elementum, libero purus scelerisque tortor, placerat consectetur sapien tellus quis elit.', 4);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Sed pellentesque quam auctor, tempus orci at, elementum diam.', 5);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Suspendisse et metus in ex suscipit consequat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 5);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Cras blandit ipsum sit amet diam hendrerit aliquet.', 5);
INSERT INTO answers (is_answer, text, question_id) VALUES (true, 'Ut sed tortor risus. Donec aliquam mollis porttitor. Cras quis metus at augue condimentum tincidunt tempor sit amet arcu.', 5);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Suspendisse volutpat urna eu orci facilisis faucibus. Sed faucibus tellus in quam scelerisque porttitor.', 6);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Maecenas ac dui id tellus elementum maximus id dictum lacus. Nunc dapibus iaculis ullamcorper.', 6);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla felis dui, sodales et pulvinar ac, tincidunt nec dolor. Aenean imperdiet orci pretium lectus scelerisque ultricies.', 6);
INSERT INTO answers (is_answer, text, question_id) VALUES (true, 'Fusce vestibulum feugiat molestie. Aenean vulputate arcu ex, sed semper ante pharetra non. Ut cursus urna non pharetra mollis. Aliquam vel facilisis ipsum, quis pharetra eros.', 6);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Maecenas convallis mollis risus in dapibus.', 7);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Aliquam viverra tempor orci a convallis.', 7);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Donec scelerisque, ipsum ut consequat elementum, libero purus scelerisque tortor, placerat consectetur sapien tellus quis elit.', 7);
INSERT INTO answers (is_answer, text, question_id) VALUES (true, 'Sed pellentesque quam auctor, tempus orci at, elementum diam.', 7);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Suspendisse et metus in ex suscipit consequat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 8);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Cras blandit ipsum sit amet diam hendrerit aliquet.', 8);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Ut sed tortor risus. Donec aliquam mollis porttitor. Cras quis metus at augue condimentum tincidunt tempor sit amet arcu.', 8);
INSERT INTO answers (is_answer, text, question_id) VALUES (true, 'Suspendisse volutpat urna eu orci facilisis faucibus. Sed faucibus tellus in quam scelerisque porttitor.', 8);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Maecenas ac dui id tellus elementum maximus id dictum lacus. Nunc dapibus iaculis ullamcorper.', 9);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla felis dui, sodales et pulvinar ac, tincidunt nec dolor. Aenean imperdiet orci pretium lectus scelerisque ultricies.', 9);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Fusce vestibulum feugiat molestie. Aenean vulputate arcu ex, sed semper ante pharetra non. Ut cursus urna non pharetra mollis. Aliquam vel facilisis ipsum, quis pharetra eros.', 9);
INSERT INTO answers (is_answer, text, question_id) VALUES (true, 'Maecenas convallis mollis risus in dapibus.', 9);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Aliquam viverra tempor orci a convallis.', 10);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Donec scelerisque, ipsum ut consequat elementum, libero purus scelerisque tortor, placerat consectetur sapien tellus quis elit.', 10);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Sed pellentesque quam auctor, tempus orci at, elementum diam.', 10);
INSERT INTO answers (is_answer, text, question_id) VALUES (true, 'Suspendisse et metus in ex suscipit consequat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 10);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Cras blandit ipsum sit amet diam hendrerit aliquet.', 11);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Ut sed tortor risus. Donec aliquam mollis porttitor. Cras quis metus at augue condimentum tincidunt tempor sit amet arcu.', 11);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Suspendisse volutpat urna eu orci facilisis faucibus. Sed faucibus tellus in quam scelerisque porttitor.', 11);
INSERT INTO answers (is_answer, text, question_id) VALUES (true, 'Maecenas ac dui id tellus elementum maximus id dictum lacus. Nunc dapibus iaculis ullamcorper.', 11);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla felis dui, sodales et pulvinar ac, tincidunt nec dolor. Aenean imperdiet orci pretium lectus scelerisque ultricies.', 12);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Fusce vestibulum feugiat molestie. Aenean vulputate arcu ex, sed semper ante pharetra non. Ut cursus urna non pharetra mollis. Aliquam vel facilisis ipsum, quis pharetra eros.', 12);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Maecenas convallis mollis risus in dapibus.', 12);
INSERT INTO answers (is_answer, text, question_id) VALUES (true, 'Aliquam viverra tempor orci a convallis.', 12);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Donec scelerisque, ipsum ut consequat elementum, libero purus scelerisque tortor, placerat consectetur sapien tellus quis elit.', 13);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Sed pellentesque quam auctor, tempus orci at, elementum diam.', 13);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Suspendisse et metus in ex suscipit consequat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 13);
INSERT INTO answers (is_answer, text, question_id) VALUES (true, 'Cras blandit ipsum sit amet diam hendrerit aliquet.', 13);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Ut sed tortor risus. Donec aliquam mollis porttitor. Cras quis metus at augue condimentum tincidunt tempor sit amet arcu.', 14);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Suspendisse volutpat urna eu orci facilisis faucibus. Sed faucibus tellus in quam scelerisque porttitor.', 14);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Maecenas ac dui id tellus elementum maximus id dictum lacus. Nunc dapibus iaculis ullamcorper.', 14);
INSERT INTO answers (is_answer, text, question_id) VALUES (true, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla felis dui, sodales et pulvinar ac, tincidunt nec dolor. Aenean imperdiet orci pretium lectus scelerisque ultricies.', 14);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Fusce vestibulum feugiat molestie. Aenean vulputate arcu ex, sed semper ante pharetra non. Ut cursus urna non pharetra mollis. Aliquam vel facilisis ipsum, quis pharetra eros.', 15);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Maecenas convallis mollis risus in dapibus.', 15);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Aliquam viverra tempor orci a convallis.', 15);
INSERT INTO answers (is_answer, text, question_id) VALUES (true, 'Donec scelerisque, ipsum ut consequat elementum, libero purus scelerisque tortor, placerat consectetur sapien tellus quis elit.', 15);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Sed pellentesque quam auctor, tempus orci at, elementum diam.', 16);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Suspendisse et metus in ex suscipit consequat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 16);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Cras blandit ipsum sit amet diam hendrerit aliquet.', 16);
INSERT INTO answers (is_answer, text, question_id) VALUES (true, 'Ut sed tortor risus. Donec aliquam mollis porttitor. Cras quis metus at augue condimentum tincidunt tempor sit amet arcu.', 16);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Suspendisse volutpat urna eu orci facilisis faucibus. Sed faucibus tellus in quam scelerisque porttitor.', 17);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Maecenas ac dui id tellus elementum maximus id dictum lacus. Nunc dapibus iaculis ullamcorper.', 17);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla felis dui, sodales et pulvinar ac, tincidunt nec dolor. Aenean imperdiet orci pretium lectus scelerisque ultricies.', 17);
INSERT INTO answers (is_answer, text, question_id) VALUES (true, 'Fusce vestibulum feugiat molestie. Aenean vulputate arcu ex, sed semper ante pharetra non. Ut cursus urna non pharetra mollis. Aliquam vel facilisis ipsum, quis pharetra eros.', 17);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Maecenas convallis mollis risus in dapibus.', 18);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Aliquam viverra tempor orci a convallis.', 18);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Donec scelerisque, ipsum ut consequat elementum, libero purus scelerisque tortor, placerat consectetur sapien tellus quis elit.', 18);
INSERT INTO answers (is_answer, text, question_id) VALUES (true, 'Sed pellentesque quam auctor, tempus orci at, elementum diam.', 18);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Suspendisse et metus in ex suscipit consequat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 19);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Cras blandit ipsum sit amet diam hendrerit aliquet.', 19);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Ut sed tortor risus. Donec aliquam mollis porttitor. Cras quis metus at augue condimentum tincidunt tempor sit amet arcu.', 19);
INSERT INTO answers (is_answer, text, question_id) VALUES (true, 'Suspendisse volutpat urna eu orci facilisis faucibus. Sed faucibus tellus in quam scelerisque porttitor.', 19);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Maecenas ac dui id tellus elementum maximus id dictum lacus. Nunc dapibus iaculis ullamcorper.', 20);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla felis dui, sodales et pulvinar ac, tincidunt nec dolor. Aenean imperdiet orci pretium lectus scelerisque ultricies.', 20);
INSERT INTO answers (is_answer, text, question_id) VALUES (false, 'Fusce vestibulum feugiat molestie. Aenean vulputate arcu ex, sed semper ante pharetra non. Ut cursus urna non pharetra mollis. Aliquam vel facilisis ipsum, quis pharetra eros.', 20);
INSERT INTO answers (is_answer, text, question_id) VALUES (true, 'Maecenas convallis mollis risus in dapibus.', 20);
