INSERT INTO questions (quiz_id, question, choice_a, choice_b, choice_c, answer) VALUES (1, 'What colour is the sky?', 'Green', 'Red', 'Brown', 'Blue');
INSERT INTO questions (quiz_id, question, choice_a, choice_b, choice_c, answer) VALUES (1, 'What element does N represent on the periodic table?', 'Oxygen', 'Gold', 'Helium', 'Nitrogen');
INSERT INTO questions (quiz_id, question, choice_a, choice_b, choice_c, answer) VALUES (1, 'What is the name of the river that runs through Egypt?', 'The Amazon', 'The Ganges', 'The Thames', 'The Nile');
INSERT INTO questions (quiz_id, question, choice_a, choice_b, choice_c, answer) VALUES (2, 'How many legs does a spider have?', '6', '4', '12', '8');
INSERT INTO questions (quiz_id, question, choice_a, choice_b, choice_c, answer) VALUES (2, 'What is the name of the toy cowboy in Toy Story?', 'Buzz Lightyear', 'Mr. Potato Head', 'Andy', 'Woody');
INSERT INTO questions (quiz_id, question, choice_a, choice_b, choice_c, answer) VALUES (2, 'What is the color of an emerald?', 'Red', 'Blue', 'Black', 'Green');
INSERT INTO questions (quiz_id, question, choice_a, choice_b, choice_c, answer) VALUES (3, 'What is something you should hit with a hammer?', 'A Feather', 'A Sandwich', 'A Thumb', 'A Nail');
INSERT INTO questions (quiz_id, question, choice_a, choice_b, choice_c, answer) VALUES (3, 'What’s the name of a place you go to see lots of animals?', 'Police Station', 'Grocery Store', 'Airport', 'Zoo');
INSERT INTO questions (quiz_id, question, choice_a, choice_b, choice_c, answer) VALUES (3, 'Whose nose grew longer every time he lied?', 'Alfred', 'Woody', 'Pagliacci', 'Pinocchio');
INSERT INTO questions (quiz_id, question, choice_a, choice_b, choice_c, answer) VALUES (4, 'What is the name of the fairy in Peter Pan?', 'Ruben', 'Siri', 'Cinderella', 'Tinkerbell');
INSERT INTO questions (quiz_id, question, choice_a, choice_b, choice_c, answer) VALUES (4, 'If you freeze water, what do you get?', 'Chicken', 'Lo Mein', 'Nostradamus', 'Ice');
INSERT INTO questions (quiz_id, question, choice_a, choice_b, choice_c, answer) VALUES (4, 'What colors are the stars on the American flag?', 'Red', 'Blue', 'Yellow', 'White');
INSERT INTO questions (quiz_id, question, choice_a, choice_b, choice_c, answer) VALUES (1, 'In the nursery rhyme, Jack and Jill, what do Jack and Jill go up the hill to fetch?', 'Magic Beans', 'Golden Goose', 'Their mother', 'A pail of water');
INSERT INTO questions (quiz_id, question, choice_a, choice_b, choice_c, answer) VALUES (5, 'How many planets are in our solar system?', '9', '7', '10', '8');
INSERT INTO questions (quiz_id, question, choice_a, choice_b, choice_c, answer) VALUES (5, 'What fruit do kids traditionally give to teachers?', 'Orange', 'Banana', 'Kiwi', 'Apple');
INSERT INTO questions (quiz_id, question, choice_a, choice_b, choice_c, answer) VALUES (5, 'Which state is famous for Hollywood?', 'Delaware', 'Wyoming', 'Kentucky', 'California');
INSERT INTO questions (quiz_id, question, choice_a, choice_b, choice_c, answer) VALUES (6, 'What type of fish is Nemo?', 'Shark', 'Squid', 'Barracuda', 'Clown Fish');
INSERT INTO questions (quiz_id, question, choice_a, choice_b, choice_c, answer) VALUES (6, 'Where is the Great Pyramid of Giza?', 'Mexico', 'Dubai', 'Las Vegas', 'Egypt');
INSERT INTO questions (quiz_id, question, choice_a, choice_b, choice_c, answer) VALUES (6, 'What do bees make?', 'Aligators', 'Jam', 'New Laws', 'Honey');
INSERT INTO questions (quiz_id, question, choice_a, choice_b, choice_c, answer) VALUES (7, 'Who wrote Hamlet?', 'J.J. Abrams', 'Nic Pizzolatto', 'Manuel Neuer', 'William Shakespeare');

