DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS quizes CASCADE;
DROP TABLE IF EXISTS questions CASCADE;
DROP TABLE IF EXISTS answers CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS quiz_category CASCADE;
DROP TABLE IF EXISTS quiz_attempts CASCADE;
DROP TABLE IF EXISTS ratings CASCADE;
DROP TABLE IF EXISTS widgets CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE quizes (
  id SERIAL PRIMARY KEY NOT NULL,
  owner_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMP,
  public BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE questions (
  id SERIAL PRIMARY KEY NOT NULL,
  text TEXT NOT NULL,
  quiz_id INTEGER REFERENCES quizes(id) ON DELETE CASCADE
);

CREATE TABLE answers (
  id SERIAL PRIMARY KEY NOT NULL,
  text TEXT NOT NULL,
  question_id INTEGER REFERENCES questions(id) ON DELETE CASCADE
);

CREATE TABLE categories (
  id SERIAL PRIMARY KEY NOT NULL,
  type VARCHAR(255) NOT NULL
);

CREATE TABLE quiz_category (
  id SERIAL PRIMARY KEY NOT NULL,
  category_id INTEGER REFERENCES categories(id) ON DELETE CASCADE,
  quiz_id INTEGER REFERENCES quizes(id) ON DELETE CASCADE
);

CREATE TABLE quiz_attempts (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  quiz_id INTEGER REFERENCES quizes(id) ON DELETE CASCADE,
  created_at TIMESTAMP,
  attempts INTEGER
);

CREATE TABLE ratings (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  quiz_id INTEGER REFERENCES quizes(id) ON DELETE CASCADE,
  rating SMALLINT NOT NULL DEFAULT 0
);
